name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setunsecureenv
      run: echo "ACTIONS_ALLOW_UNSECURE_COMMANDS=true" >> "${GITHUB_ENV}"
    - name: path
      run: echo "${{github.workspace}}/tools/bin" >> "${GITHUB_PATH}"
    - name: make
      run: make N=1 -j$(nproc)
    - uses: actions/upload-artifact@v2
      with:
        name: winix.srec
        path: winix.srec
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install pip packages
      run: pip install bs4
    - name: run unit test
      run: make test

